-- ============================================================================
-- METADATA-DRIVEN TAX FORMS - SAMPLE DATA
-- ============================================================================
-- FOR AI AGENT: Execute these scripts AFTER creating tables from PRD document
-- ============================================================================

-- ============================================================================
-- DROPDOWN CONFIGURATIONS
-- ============================================================================

-- Federal Tax Classification (W9)
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('FEDERAL_TAX_CLASSIFICATION', 'Federal Tax Classification', 'W9 entity types', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'INDIVIDUAL', 'Individual/Sole Proprietor', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'C_CORP', 'C Corporation', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'S_CORP', 'S Corporation', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'PARTNERSHIP', 'Partnership', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'TRUST_ESTATE', 'Trust/Estate', 5);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('FEDERAL_TAX_CLASSIFICATION', 'LLC', 'Limited Liability Company', 6);

-- LLC Classification
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('LLC_CLASSIFICATION', 'LLC Tax Classification', 'Tax classification for LLCs', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('LLC_CLASSIFICATION', 'C', 'C Corporation', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('LLC_CLASSIFICATION', 'S', 'S Corporation', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('LLC_CLASSIFICATION', 'P', 'Partnership', 3);

-- TIN Types
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('TIN_TYPES', 'Taxpayer ID Types', 'SSN or EIN selection', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('TIN_TYPES', 'SSN', 'Social Security Number', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('TIN_TYPES', 'EIN', 'Employer Identification Number', 2);

-- US States
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('US_STATES', 'US States', 'All US states and territories', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'AL', 'Alabama', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'AK', 'Alaska', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'AZ', 'Arizona', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'CA', 'California', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'CO', 'Colorado', 5);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'CT', 'Connecticut', 6);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'DE', 'Delaware', 7);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'FL', 'Florida', 8);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'GA', 'Georgia', 9);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'NY', 'New York', 10);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('US_STATES', 'TX', 'Texas', 11);
-- Add remaining states as needed

-- Chapter 3 Status (W8-BEN-E)
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('CHAPTER3_STATUS', 'Chapter 3 Status', 'Entity types for W8-BEN-E', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'CORPORATION', 'Corporation', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'PARTNERSHIP', 'Partnership', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'SIMPLE_TRUST', 'Simple Trust', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'GRANTOR_TRUST', 'Grantor Trust', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'COMPLEX_TRUST', 'Complex Trust', 5);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'ESTATE', 'Estate', 6);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'GOVERNMENT', 'Government', 7);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'CENTRAL_BANK', 'Central Bank of Issue', 8);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'TAX_EXEMPT_ORG', 'Tax-Exempt Organization', 9);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'PRIVATE_FOUNDATION', 'Private Foundation', 10);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER3_STATUS', 'INTERNATIONAL_ORG', 'International Organization', 11);

-- Chapter 4 Status (FATCA)
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('CHAPTER4_STATUS', 'Chapter 4 Status (FATCA)', 'FATCA status for entities', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER4_STATUS', 'ACTIVE_NFFE', 'Active NFFE', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER4_STATUS', 'PASSIVE_NFFE', 'Passive NFFE', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER4_STATUS', 'PARTICIPATING_FFI', 'Participating FFI', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER4_STATUS', 'REPORTING_MODEL1_FFI', 'Reporting Model 1 FFI', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('CHAPTER4_STATUS', 'REPORTING_MODEL2_FFI', 'Reporting Model 2 FFI', 5);

-- Countries (Partial list - add more as needed)
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('COUNTRIES', 'Countries', 'All countries list', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'US', 'United States', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'UK', 'United Kingdom', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'CA', 'Canada', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'DE', 'Germany', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'FR', 'France', 5);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'JP', 'Japan', 6);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'AU', 'Australia', 7);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'IN', 'India', 8);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'CN', 'China', 9);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('COUNTRIES', 'BR', 'Brazil', 10);
-- Add remaining countries as needed

-- Treaty Countries
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('TREATY_COUNTRIES', 'Treaty Countries', 'Countries with US tax treaties', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'UK', 'United Kingdom', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'CA', 'Canada', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'DE', 'Germany', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'FR', 'France', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'JP', 'Japan', 5);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'AU', 'Australia', 6);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES ('TREATY_COUNTRIES', 'IN', 'India', 7);

-- Income Types
INSERT INTO DROPDOWN_CONFIGS (CONFIG_KEY, CONFIG_NAME, DESCRIPTION, STATUS) 
VALUES ('INCOME_TYPES', 'Income Types', 'Types of income for treaty claims', 'ACTIVE');

INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('INCOME_TYPES', 'DIVIDENDS', 'Dividends', 1);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('INCOME_TYPES', 'INTEREST', 'Interest', 2);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('INCOME_TYPES', 'ROYALTIES', 'Royalties', 3);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('INCOME_TYPES', 'SERVICES', 'Services', 4);
INSERT INTO DROPDOWN_VALUES (CONFIG_KEY, VALUE_CODE, DISPLAY_TEXT, DISPLAY_ORDER) VALUES
('INCOME_TYPES', 'OTHER', 'Other Income', 5);

-- ============================================================================
-- W9 FORM TEMPLATE
-- ============================================================================

INSERT INTO FORM_TEMPLATES (FORM_CODE, FORM_NAME, FORM_DESCRIPTION, FORM_VERSION, STATUS, CREATED_BY)
VALUES ('W9', 'Request for Taxpayer Identification Number and Certification', 
        'Form W-9 is used to request taxpayer identification number (TIN) and certification', 
        1.0, 'ACTIVE', 'SYSTEM');

-- Get the FORM_ID for W9 (assume it's 1 for fresh database)
-- Section 1: Basic Information
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (1, 'BASIC_INFO', 'Part I - Taxpayer Identification', 1, 1, 1, 'N', 'Basic taxpayer information', 'ACTIVE');

-- Section 2: Address
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (1, 'ADDRESS', 'Address', 2, 1, 1, 'N', 'Taxpayer address information', 'ACTIVE');

-- Section 3: Taxpayer ID
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (1, 'TAXPAYER_ID', 'Taxpayer Identification Number', 3, 1, 1, 'N', 'TIN information', 'ACTIVE');

-- Section 4: Certification
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (1, 'CERTIFICATION', 'Part II - Certification', 4, 1, 1, 'N', 'Certification and signature', 'ACTIVE');

-- ============================================================================
-- W9 FORM FIELDS
-- ============================================================================

-- Basic Info Fields (Section ID = 1)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, PLACEHOLDER_TEXT, COL_SPAN, STATUS)
VALUES (1, 'NAME', 'Name (as shown on your income tax return)', 'TEXT', 1, 'Y', 100, 'Enter your full legal name', 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, HELP_TEXT, COL_SPAN, STATUS)
VALUES (1, 'BUSINESS_NAME', 'Business name/disregarded entity name', 'TEXT', 2, 'N', 100, 'If different from above', 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (1, 'FEDERAL_TAX_CLASSIFICATION', 'Federal tax classification', 'DROPDOWN', 3, 'Y', 'FEDERAL_TAX_CLASSIFICATION', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, HELP_TEXT, COL_SPAN, STATUS)
VALUES (1, 'LLC_CLASSIFICATION', 'LLC Classification', 'DROPDOWN', 4, 'N', 'LLC_CLASSIFICATION', 'Required if LLC is selected above', 6, 'ACTIVE');

-- Address Fields (Section ID = 2)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (2, 'STREET_ADDRESS', 'Address (number, street, and apt. or suite no.)', 'TEXT', 1, 'Y', 200, 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (2, 'CITY', 'City', 'TEXT', 2, 'Y', 100, 5, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (2, 'STATE', 'State', 'DROPDOWN', 3, 'Y', 'US_STATES', 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, VALIDATION_REGEX, PLACEHOLDER_TEXT, COL_SPAN, STATUS)
VALUES (2, 'ZIP_CODE', 'ZIP Code', 'TEXT', 4, 'Y', 10, '^[0-9]{5}(-[0-9]{4})?$', '12345', 3, 'ACTIVE');

-- Taxpayer ID Fields (Section ID = 3)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (3, 'TIN_TYPE', 'TIN Type', 'RADIO', 1, 'Y', 'TIN_TYPES', 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, VALIDATION_REGEX, PLACEHOLDER_TEXT, COL_SPAN, STATUS)
VALUES (3, 'SSN', 'Social Security Number', 'SSN', 2, 'N', '^[0-9]{3}-[0-9]{2}-[0-9]{4}$', 'XXX-XX-XXXX', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, VALIDATION_REGEX, PLACEHOLDER_TEXT, COL_SPAN, STATUS)
VALUES (3, 'EIN', 'Employer Identification Number', 'EIN', 3, 'N', '^[0-9]{2}-[0-9]{7}$', 'XX-XXXXXXX', 6, 'ACTIVE');

-- Certification Fields (Section ID = 4)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (4, 'CERTIFICATION_AGREE', 'I certify that the information provided is accurate', 'CHECKBOX', 1, 'Y', 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (4, 'SIGNATURE', 'Signature', 'SIGNATURE', 2, 'Y', 8, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (4, 'SIGNATURE_DATE', 'Date', 'DATE', 3, 'Y', 4, 'ACTIVE');

-- ============================================================================
-- W8-BEN-E FORM TEMPLATE (with repeatable section)
-- ============================================================================

INSERT INTO FORM_TEMPLATES (FORM_CODE, FORM_NAME, FORM_DESCRIPTION, FORM_VERSION, STATUS, CREATED_BY)
VALUES ('W8-BEN-E', 'Certificate of Status of Beneficial Owner for U.S. Tax Withholding (Entities)', 
        'Used by foreign entities to establish foreign status and claim treaty benefits', 
        1.0, 'ACTIVE', 'SYSTEM');

-- Sections for W8-BEN-E (FORM_ID = 2)
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (2, 'BENEFICIAL_OWNER', 'Part I - Identification of Beneficial Owner', 1, 1, 1, 'N', 'Entity identification', 'ACTIVE');

INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (2, 'PERMANENT_ADDRESS', 'Permanent Residence Address', 2, 1, 1, 'N', 'Permanent address of entity', 'ACTIVE');

-- REPEATABLE SECTION: Treaty Claims (can have 0-10 occurrences)
INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (2, 'TREATY_CLAIMS', 'Part III - Claim of Tax Treaty Benefits', 3, 0, 10, 'Y', 'Add treaty claims for different income types', 'ACTIVE');

INSERT INTO FORM_SECTIONS (FORM_ID, SECTION_CODE, SECTION_NAME, DISPLAY_ORDER, MIN_OCCURRENCES, MAX_OCCURRENCES, IS_REPEATABLE, SECTION_DESCRIPTION, STATUS)
VALUES (2, 'CERTIFICATION', 'Part XXX - Certification', 4, 1, 1, 'N', 'Certification and signature', 'ACTIVE');

-- ============================================================================
-- W8-BEN-E FORM FIELDS
-- ============================================================================

-- Beneficial Owner Fields (Section ID = 5)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (5, 'ORG_NAME', 'Name of organization', 'TEXT', 1, 'Y', 200, 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (5, 'COUNTRY_OF_INCORPORATION', 'Country of incorporation or organization', 'COUNTRY_SELECTOR', 2, 'Y', 'COUNTRIES', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (5, 'CHAPTER3_STATUS', 'Chapter 3 Status (entity type)', 'DROPDOWN', 3, 'Y', 'CHAPTER3_STATUS', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (5, 'CHAPTER4_STATUS', 'Chapter 4 Status (FATCA status)', 'DROPDOWN', 4, 'Y', 'CHAPTER4_STATUS', 6, 'ACTIVE');

-- Permanent Address Fields (Section ID = 6)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (6, 'STREET_ADDRESS', 'Street address', 'TEXT', 1, 'Y', 200, 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (6, 'CITY', 'City or town', 'TEXT', 2, 'Y', 100, 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (6, 'STATE_PROVINCE', 'State or province', 'TEXT', 3, 'N', 100, 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (6, 'COUNTRY', 'Country', 'COUNTRY_SELECTOR', 4, 'Y', 'COUNTRIES', 4, 'ACTIVE');

-- Treaty Claims Fields (Section ID = 7) - REPEATABLE SECTION
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (7, 'TREATY_COUNTRY', 'Treaty Country', 'COUNTRY_SELECTOR', 1, 'Y', 'TREATY_COUNTRIES', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, DROPDOWN_CONFIG_KEY, COL_SPAN, STATUS)
VALUES (7, 'INCOME_TYPE', 'Type of Income', 'DROPDOWN', 2, 'Y', 'INCOME_TYPES', 6, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, PLACEHOLDER_TEXT, COL_SPAN, STATUS)
VALUES (7, 'TREATY_ARTICLE', 'Article Number', 'TEXT', 3, 'Y', 20, 'e.g., Article 10', 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MIN_VALUE, MAX_VALUE, COL_SPAN, STATUS)
VALUES (7, 'WITHHOLDING_RATE', 'Withholding Rate (%)', 'NUMBER', 4, 'Y', 0, 100, 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, MAX_LENGTH, COL_SPAN, STATUS)
VALUES (7, 'TREATY_JUSTIFICATION', 'Explanation of treaty benefits claimed', 'TEXTAREA', 5, 'Y', 1000, 12, 'ACTIVE');

-- Certification Fields for W8-BEN-E (Section ID = 8)
INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (8, 'CERTIFICATION_AGREE', 'I certify that the entity is the beneficial owner of all payments', 'CHECKBOX', 1, 'Y', 12, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (8, 'SIGNATURE', 'Signature of authorized individual', 'SIGNATURE', 2, 'Y', 8, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (8, 'SIGNER_NAME', 'Print name of signer', 'TEXT', 3, 'Y', 4, 'ACTIVE');

INSERT INTO FORM_FIELDS (SECTION_ID, FIELD_CODE, FIELD_LABEL, FIELD_TYPE, DISPLAY_ORDER, IS_REQUIRED, COL_SPAN, STATUS)
VALUES (8, 'SIGNATURE_DATE', 'Date', 'DATE', 4, 'Y', 4, 'ACTIVE');

COMMIT;
